-- Best practices demonstrated:
-- - Explicit column constraints (NOT NULL, UNIQUE) at the DB level as a second safety net
--   behind the JPA/validation layer — defence in depth
-- - VARCHAR lengths match JPA @Column(length = N) definitions exactly
-- - Indexes on frequently queried columns (username, email, active) avoid full-table scans
-- - TIMESTAMP WITH TIME ZONE stores instants without losing offset information
-- - Table named "users" avoids the reserved word "user" in most SQL dialects

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL,
    email      VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX idx_users_active ON users (active);
